### ISSUE TITLE
Configurations for Atari games

### ISSUE THREAD

**Issue by fuxianh** [Kaixhin/ACER#18]
Hello, @Kaixhin . I am very glad to find your implemention for ACER in pytorch, and I want to do something based on it. However, I want to test on Atari games(pixel games) instead of Cartpole (control games). There are a lot of hyper-parameters, I wonder if I need to tune them or keep them as provided by you? Looking forward to your reply.

**Comment by Kaixhin** [comment]
You will need to use the hyperparameters from the original paper, plus adjust the neural network model to have convolutional layers (again, the paper should specify the architecture they used).

**Comment by fuxianh** [comment]
Thank you so much, I will check the hyperparameters from the original paper. By the way, have you test some Atari games with your code? How is the performance?

**Comment by Kaixhin** [comment]
No, I haven't tested my code with any other environments.

**Comment by fuxianh** [comment]
All right.  Thanks again for your advice.
