### ISSUE TITLE
the code of the off-policy bias correction

### ISSUE THREAD

**Issue by ChangTang210** [Kaixhin/ACER#22]
Hello, i have a question about the loss, thanks.

Does bias correction loss miss the item of policies?

![image](https://user-images.githubusercontent.com/49151874/222621276-d8266a5c-6d31-4459-a2b0-4e585c3d12cd.png)

**Comment by Kaixhin** [comment]
Should be `policies[i]` at the end of https://github.com/Kaixhin/ACER/blob/master/train.py#L106 .
