### ISSUE TITLE
feed the previous action to lstm

### ISSUE THREAD

**Issue by jingweiz** [Kaixhin/ACER#3]
Hey,
nice work! One quick question, you mentioned ```The agent also receives the previous action and reward```, but this part is not part of the acer algorithm, but only from the navigation paper right?

**Comment by Kaixhin** [comment]
Yep I just kind of added it by habit. I don't think it actually makes much of a difference, so I think I'll remove it and keep this as a canonical implementation of ACER (minus the "efficient" trust region bit - [still thinking how best to do that](https://discuss.pytorch.org/t/truncating-backprop-temporarily/4974)).

**Comment by Kaixhin** [comment]
It still works (kind of, or the same as before at least).

![newplot](https://user-images.githubusercontent.com/991891/28421827-314961b0-6d5e-11e7-8603-d66f9be0d3c7.png)

**Comment by jingweiz** [comment]
Thanks a lot for the reply :)
