### ISSUE TITLE
Doubts on Episodic Memory

### ISSUE THREAD

**Issue by mirraaj** [Kaixhin/ACER#7]
https://github.com/Kaixhin/ACER/blob/5b7ca5d75bf16629ddaf68ecab4ab6c7dcccf56c/main.py#L25

Hello Kaixhin,

I do not get the idea of you using memory capacity greater that T_MAX. Shouldn't the implementation have memory capacity be less than the T_MAX. This looks more intuitive to me. Please let me know what do you think.

**Comment by Kaixhin** [comment]
You're right, there's no point to having the memory capacity be greater than the number of samples it could ever receive. Fixed to something perhaps more reasonable.
